export const STORE_INGREDIENTS = "STORE_INGREDIENTS";
export const ERROR_STORING_INGREDIENTS = "ERROR_STORING_INGREDIENTS";
export const ADD_ING = "ADD_ING";
export const REMOVE_ING = "REMOVE_ING";

export const ORDER_SUBMIT_SUCCESS = "ORDER_SUBMIT_SUCCESS";
export const ORDER_SUBMIT_FAIL = "ORDER_SUBMIT_FAIL";