export const STORE_INGREDIENTS = "STORE_INGREDIENTS";
export const ERROR_STORING_INGREDIENTS = "ERROR_STORING_INGREDIENTS";
export const ADD_ING = "ADD_ING";
export const REMOVE_ING = "REMOVE_ING";
export const RESET_BUTTON = "RESET_BUTTON";

export const ORDER_SUBMIT_SUCCESS = "ORDER_SUBMIT_SUCCESS";
export const ORDER_SUBMIT_FAIL = "ORDER_SUBMIT_FAIL";
export const STORE_FETCHED_ORDERS = "STORE_FETCHED_ORDERS";
export const WAIT_FETCH_ORDERS = "WAIT_FETCH_ORDERS";
export const ERROR_FETCHING_ORDERS = "ERROR_FETCHING_ORDERS";
export const WAIT_ORDER_SUBMIT_RESPONSE = "WAIT_ORDER_SUBMIT_RESPONSE";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const WAIT_AUTH = "WAIT_AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const SET_REDIRECT_PATH = "REDIRECT_PATH";